ALTER TABLE users ADD COLUMN IF NOT EXISTS notif_breakfast_enabled BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS notif_breakfast_time VARCHAR(5) NOT NULL DEFAULT '07:30';
ALTER TABLE users ADD COLUMN IF NOT EXISTS notif_dinner_enabled BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS notif_dinner_time VARCHAR(5) NOT NULL DEFAULT '17:30';
