//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0



use sea_orm :: entity :: prelude :: * ;

# [derive (Clone , Debug , PartialEq , Eq , DeriveEntityModel)] # [sea_orm (table_name = "api_keys")] pub struct Model { # [sea_orm (primary_key , auto_increment = false)] pub id : Uuid , pub project_id : Uuid , pub user_id : Uuid , # [sea_orm (unique)] pub key_hash : String , pub key_prefix : String , pub name : String , pub tier : String , pub is_active : bool , pub created_at : Option < DateTimeWithTimeZone > , pub updated_at : Option < DateTimeWithTimeZone > , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { # [sea_orm (has_many = "super::api_usage_logs::Entity")] ApiUsageLogs , # [sea_orm (belongs_to = "super::projects::Entity" , from = "Column::ProjectId" , to = "super::projects::Column::Id" , on_update = "NoAction" , on_delete = "Cascade" ,)] Projects , # [sea_orm (belongs_to = "super::users::Entity" , from = "Column::UserId" , to = "super::users::Column::Id" , on_update = "NoAction" , on_delete = "Cascade" ,)] Users , }

impl Related < super :: api_usage_logs :: Entity > for Entity { fn to () -> RelationDef { Relation :: ApiUsageLogs . def () } }

impl Related < super :: projects :: Entity > for Entity { fn to () -> RelationDef { Relation :: Projects . def () } }

impl Related < super :: users :: Entity > for Entity { fn to () -> RelationDef { Relation :: Users . def () } }

impl ActiveModelBehavior for ActiveModel { }