//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0



use sea_orm :: entity :: prelude :: * ;

# [derive (Clone , Debug , PartialEq , Eq , DeriveEntityModel)] # [sea_orm (table_name = "api_usage_logs")] pub struct Model { # [sea_orm (primary_key)] pub id : i32 , # [sea_orm (unique_key = "api_usage_logs_api_key_id_date_key")] pub api_key_id : Uuid , # [sea_orm (unique_key = "api_usage_logs_api_key_id_date_key")] pub date : Date , pub requests : i32 , pub errors : i32 , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { # [sea_orm (belongs_to = "super::api_keys::Entity" , from = "Column::ApiKeyId" , to = "super::api_keys::Column::Id" , on_update = "NoAction" , on_delete = "Cascade" ,)] ApiKeys , }

impl Related < super :: api_keys :: Entity > for Entity { fn to () -> RelationDef { Relation :: ApiKeys . def () } }

impl ActiveModelBehavior for ActiveModel { }