//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0



use sea_orm :: entity :: prelude :: * ;

# [derive (Clone , Debug , PartialEq , Eq , DeriveEntityModel)] # [sea_orm (table_name = "badges")] pub struct Model { # [sea_orm (primary_key)] pub id : i32 , # [sea_orm (unique)] pub name : String , # [sea_orm (column_type = "Text" , nullable)] pub description : Option < String > , pub icon_url : Option < String > , pub created_at : Option < DateTimeWithTimeZone > , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { # [sea_orm (has_many = "super::user_badges::Entity")] UserBadges , }

impl Related < super :: user_badges :: Entity > for Entity { fn to () -> RelationDef { Relation :: UserBadges . def () } }

impl Related < super :: users :: Entity > for Entity { fn to () -> RelationDef { super :: user_badges :: Relation :: Users . def () } fn via () -> Option < RelationDef > { Some (super :: user_badges :: Relation :: Badges . def () . rev ()) } }

impl ActiveModelBehavior for ActiveModel { }