//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0



use sea_orm :: entity :: prelude :: * ;

# [derive (Clone , Debug , PartialEq , Eq , DeriveEntityModel)] # [sea_orm (table_name = "cities")] pub struct Model { # [sea_orm (primary_key)] pub id : i32 , pub name : String , # [sea_orm (unique)] pub slug : String , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { # [sea_orm (has_many = "super::menu_history::Entity")] MenuHistory , # [sea_orm (has_many = "super::menu_submissions::Entity")] MenuSubmissions , # [sea_orm (has_many = "super::menus::Entity")] Menus , # [sea_orm (has_many = "super::users::Entity")] Users , }

impl Related < super :: menu_history :: Entity > for Entity { fn to () -> RelationDef { Relation :: MenuHistory . def () } }

impl Related < super :: menu_submissions :: Entity > for Entity { fn to () -> RelationDef { Relation :: MenuSubmissions . def () } }

impl Related < super :: menus :: Entity > for Entity { fn to () -> RelationDef { Relation :: Menus . def () } }

impl Related < super :: users :: Entity > for Entity { fn to () -> RelationDef { Relation :: Users . def () } }

impl ActiveModelBehavior for ActiveModel { }