//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0



use sea_orm :: entity :: prelude :: * ; use super :: sea_orm_active_enums :: SentimentEnum ;

# [derive (Clone , Debug , PartialEq , Eq , DeriveEntityModel)] # [sea_orm (table_name = "comments")] pub struct Model { # [sea_orm (primary_key , auto_increment = false)] pub id : Uuid , pub user_id : Option < Uuid > , pub menu_id : i32 , pub dish_id : Option < i32 > , pub parent_id : Option < Uuid > , # [sea_orm (column_type = "Text" , nullable)] pub content : Option < String > , pub sentiment : SentimentEnum , pub is_tabldot : bool , pub is_deleted : bool , pub reason : Option < String > , pub created_at : Option < DateTimeWithTimeZone > , pub updated_at : Option < DateTimeWithTimeZone > , pub deletion_type : Option < String > , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { # [sea_orm (belongs_to = "Entity" , from = "Column::ParentId" , to = "Column::Id" , on_update = "NoAction" , on_delete = "Cascade" ,)] SelfRef , # [sea_orm (belongs_to = "super::dishes::Entity" , from = "Column::DishId" , to = "super::dishes::Column::Id" , on_update = "NoAction" , on_delete = "Cascade" ,)] Dishes , # [sea_orm (belongs_to = "super::menus::Entity" , from = "Column::MenuId" , to = "super::menus::Column::Id" , on_update = "NoAction" , on_delete = "Cascade" ,)] Menus , # [sea_orm (has_many = "super::reports::Entity")] Reports , # [sea_orm (belongs_to = "super::users::Entity" , from = "Column::UserId" , to = "super::users::Column::Id" , on_update = "NoAction" , on_delete = "SetNull" ,)] Users , # [sea_orm (has_many = "super::vote_reactions::Entity")] VoteReactions , }

impl Related < super :: dishes :: Entity > for Entity { fn to () -> RelationDef { Relation :: Dishes . def () } }

impl Related < super :: menus :: Entity > for Entity { fn to () -> RelationDef { Relation :: Menus . def () } }

impl Related < super :: reports :: Entity > for Entity { fn to () -> RelationDef { Relation :: Reports . def () } }

impl Related < super :: users :: Entity > for Entity { fn to () -> RelationDef { Relation :: Users . def () } }

impl Related < super :: vote_reactions :: Entity > for Entity { fn to () -> RelationDef { Relation :: VoteReactions . def () } }

impl ActiveModelBehavior for ActiveModel { }