//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0



use sea_orm :: entity :: prelude :: * ; use super :: sea_orm_active_enums :: ReportStatusEnum ;

# [derive (Clone , Debug , PartialEq , Eq , DeriveEntityModel)] # [sea_orm (table_name = "contact_messages")] pub struct Model { # [sea_orm (primary_key)] pub id : i32 , pub user_id : Option < Uuid > , pub email : String , pub category : String , pub subject : String , # [sea_orm (column_type = "Text")] pub message : String , pub status : ReportStatusEnum , pub created_at : Option < DateTimeWithTimeZone > , pub resolved_at : Option < DateTimeWithTimeZone > , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { # [sea_orm (belongs_to = "super::users::Entity" , from = "Column::UserId" , to = "super::users::Column::Id" , on_update = "NoAction" , on_delete = "SetNull" ,)] Users , }

impl Related < super :: users :: Entity > for Entity { fn to () -> RelationDef { Relation :: Users . def () } }

impl ActiveModelBehavior for ActiveModel { }