//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0



use sea_orm :: entity :: prelude :: * ;

# [derive (Clone , Debug , PartialEq , Eq , DeriveEntityModel)] # [sea_orm (table_name = "dish_aliases")] pub struct Model { # [sea_orm (primary_key)] pub id : i32 , # [sea_orm (column_type = "Text" , unique)] pub name : String , pub dish_id : Option < i32 > , pub created_at : Option < DateTimeWithTimeZone > , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { # [sea_orm (belongs_to = "super::dishes::Entity" , from = "Column::DishId" , to = "super::dishes::Column::Id" , on_update = "NoAction" , on_delete = "SetNull" ,)] Dishes , # [sea_orm (has_many = "super::menu_dishes::Entity")] MenuDishes , }

impl Related < super :: dishes :: Entity > for Entity { fn to () -> RelationDef { Relation :: Dishes . def () } }

impl Related < super :: menu_dishes :: Entity > for Entity { fn to () -> RelationDef { Relation :: MenuDishes . def () } }

impl ActiveModelBehavior for ActiveModel { }