//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0



use sea_orm :: entity :: prelude :: * ;

# [derive (Clone , Debug , PartialEq , Eq , DeriveEntityModel)] # [sea_orm (table_name = "dish_tags")] pub struct Model { # [sea_orm (primary_key , auto_increment = false)] pub dish_id : i32 , # [sea_orm (primary_key , auto_increment = false)] pub tag_id : i32 , pub created_at : Option < DateTimeWithTimeZone > , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { # [sea_orm (belongs_to = "super::dishes::Entity" , from = "Column::DishId" , to = "super::dishes::Column::Id" , on_update = "NoAction" , on_delete = "Cascade" ,)] Dishes , # [sea_orm (belongs_to = "super::tags::Entity" , from = "Column::TagId" , to = "super::tags::Column::Id" , on_update = "NoAction" , on_delete = "Cascade" ,)] Tags , }

impl Related < super :: dishes :: Entity > for Entity { fn to () -> RelationDef { Relation :: Dishes . def () } }

impl Related < super :: tags :: Entity > for Entity { fn to () -> RelationDef { Relation :: Tags . def () } }

impl ActiveModelBehavior for ActiveModel { }