//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0



use sea_orm :: entity :: prelude :: * ; use super :: sea_orm_active_enums :: MealTypeEnum ; use super :: sea_orm_active_enums :: MenuStatusEnum ;

# [derive (Clone , Debug , PartialEq , Eq , DeriveEntityModel)] # [sea_orm (table_name = "menus")] pub struct Model { # [sea_orm (primary_key)] pub id : i32 , # [sea_orm (unique_key = "menus_city_id_serve_date_meal_type_key")] pub city_id : i32 , # [sea_orm (unique_key = "menus_city_id_serve_date_meal_type_key")] pub serve_date : Date , # [sea_orm (unique_key = "menus_city_id_serve_date_meal_type_key")] pub meal_type : MealTypeEnum , pub merkle_root : Option < String > , pub previous_hash : Option < String > , pub source_type : Option < String > , pub status : MenuStatusEnum , # [sea_orm (column_type = "Text" , nullable)] pub bot_commentary : Option < String > , pub created_at : Option < DateTimeWithTimeZone > , pub submitted_by : Option < Uuid > , pub calorie_range_min: Option<i32>, pub calorie_range_max: Option<i32>, }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { # [sea_orm (belongs_to = "super::cities::Entity" , from = "Column::CityId" , to = "super::cities::Column::Id" , on_update = "NoAction" , on_delete = "Cascade" ,)] Cities , # [sea_orm (has_many = "super::comments::Entity")] Comments , # [sea_orm (has_many = "super::dish_votes::Entity")] DishVotes , # [sea_orm (has_many = "super::menu_dishes::Entity")] MenuDishes , # [sea_orm (has_many = "super::menu_votes::Entity")] MenuVotes , # [sea_orm (has_many = "super::reports::Entity")] Reports , }

impl Related < super :: cities :: Entity > for Entity { fn to () -> RelationDef { Relation :: Cities . def () } }

impl Related < super :: comments :: Entity > for Entity { fn to () -> RelationDef { Relation :: Comments . def () } }

impl Related < super :: dish_votes :: Entity > for Entity { fn to () -> RelationDef { Relation :: DishVotes . def () } }

impl Related < super :: menu_dishes :: Entity > for Entity { fn to () -> RelationDef { Relation :: MenuDishes . def () } }

impl Related < super :: menu_votes :: Entity > for Entity { fn to () -> RelationDef { Relation :: MenuVotes . def () } }

impl Related < super :: reports :: Entity > for Entity { fn to () -> RelationDef { Relation :: Reports . def () } }

impl ActiveModelBehavior for ActiveModel { }