//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0



use sea_orm :: entity :: prelude :: * ;

# [derive (Clone , Debug , PartialEq , Eq , DeriveEntityModel)] # [sea_orm (table_name = "menu_dishes")] pub struct Model { # [sea_orm (primary_key)] pub id : i32 , # [sea_orm (unique_key = "menu_dishes_menu_id_dish_alias_id_package_name_key")] pub menu_id : i32 , # [sea_orm (unique_key = "menu_dishes_menu_id_dish_alias_id_package_name_key")] pub dish_alias_id : i32 , pub order_index : i32 , pub is_alternative : bool , # [sea_orm (unique_key = "menu_dishes_menu_id_dish_alias_id_package_name_key")] pub package_name : String , pub amount: Option<String>, pub calories: Option<i32>, }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { # [sea_orm (belongs_to = "super::dish_aliases::Entity" , from = "Column::DishAliasId" , to = "super::dish_aliases::Column::Id" , on_update = "NoAction" , on_delete = "Restrict" ,)] DishAliases , # [sea_orm (belongs_to = "super::menus::Entity" , from = "Column::MenuId" , to = "super::menus::Column::Id" , on_update = "NoAction" , on_delete = "Cascade" ,)] Menus , }

impl Related < super :: dish_aliases :: Entity > for Entity { fn to () -> RelationDef { Relation :: DishAliases . def () } }

impl Related < super :: menus :: Entity > for Entity { fn to () -> RelationDef { Relation :: Menus . def () } }

impl ActiveModelBehavior for ActiveModel { }