//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0



use sea_orm :: entity :: prelude :: * ;

# [derive (Clone , Debug , PartialEq , Eq , DeriveEntityModel)] # [sea_orm (table_name = "menu_submissions")] pub struct Model { # [sea_orm (primary_key)] pub id : i32 , pub user_id : Option < Uuid > , pub city_slug : String , pub year : i32 , pub month : i32 , # [sea_orm (column_type = "Text" , nullable)] pub notes : Option < String > , pub status : String , pub created_at : Option < DateTimeWithTimeZone > , pub updated_at : Option < DateTimeWithTimeZone > , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { # [sea_orm (belongs_to = "super::cities::Entity" , from = "Column::CitySlug" , to = "super::cities::Column::Slug" , on_update = "NoAction" , on_delete = "Cascade" ,)] Cities , # [sea_orm (belongs_to = "super::users::Entity" , from = "Column::UserId" , to = "super::users::Column::Id" , on_update = "NoAction" , on_delete = "SetNull" ,)] Users , }

impl Related < super :: cities :: Entity > for Entity { fn to () -> RelationDef { Relation :: Cities . def () } }

impl Related < super :: users :: Entity > for Entity { fn to () -> RelationDef { Relation :: Users . def () } }

impl ActiveModelBehavior for ActiveModel { }