//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0



use sea_orm :: entity :: prelude :: * ; use super :: sea_orm_active_enums :: SentimentEnum ;

# [derive (Clone , Debug , PartialEq , Eq , DeriveEntityModel)] # [sea_orm (table_name = "menu_votes")] pub struct Model { # [sea_orm (primary_key)] pub id : i32 , # [sea_orm (unique_key = "menu_votes_menu_id_user_id_key")] pub menu_id : i32 , # [sea_orm (unique_key = "menu_votes_menu_id_user_id_key")] pub user_id : Uuid , pub sentiment : SentimentEnum , pub created_at : Option < DateTimeWithTimeZone > , pub updated_at : Option < DateTimeWithTimeZone > , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { # [sea_orm (belongs_to = "super::menus::Entity" , from = "Column::MenuId" , to = "super::menus::Column::Id" , on_update = "NoAction" , on_delete = "Cascade" ,)] Menus , # [sea_orm (belongs_to = "super::users::Entity" , from = "Column::UserId" , to = "super::users::Column::Id" , on_update = "NoAction" , on_delete = "Cascade" ,)] Users , }

impl Related < super :: menus :: Entity > for Entity { fn to () -> RelationDef { Relation :: Menus . def () } }

impl Related < super :: users :: Entity > for Entity { fn to () -> RelationDef { Relation :: Users . def () } }

impl ActiveModelBehavior for ActiveModel { }