//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0



use sea_orm :: entity :: prelude :: * ;

# [derive (Clone , Debug , PartialEq , Eq , DeriveEntityModel)] # [sea_orm (table_name = "menu_history")] pub struct Model { # [sea_orm (primary_key)] pub id : i32 , pub city_id : i32 , pub serve_date : Date , pub meal_type : String , pub source_type : String , pub submitted_by : Option < Uuid > , # [sea_orm (column_type = "JsonBinary")] pub dishes_payload : Json , pub created_at : Option < DateTimeWithTimeZone > , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { # [sea_orm (belongs_to = "super::cities::Entity" , from = "Column::CityId" , to = "super::cities::Column::Id" , on_update = "NoAction" , on_delete = "Cascade" ,)] Cities , }

impl Related < super :: cities :: Entity > for Entity { fn to () -> RelationDef { Relation :: Cities . def () } }

impl ActiveModelBehavior for ActiveModel { }