//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0



use sea_orm :: entity :: prelude :: * ;

# [derive (Clone , Debug , PartialEq , Eq , DeriveEntityModel)] # [sea_orm (table_name = "notifications")] pub struct Model { # [sea_orm (primary_key)] pub id : i32 , pub user_id : Uuid , pub r#type : String , pub title : String , # [sea_orm (column_type = "Text")] pub message : String , pub is_read : Option < bool > , pub action_label : Option < String > , pub action_href : Option < String > , pub created_at : Option < DateTimeWithTimeZone > , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { # [sea_orm (belongs_to = "super::users::Entity" , from = "Column::UserId" , to = "super::users::Column::Id" , on_update = "NoAction" , on_delete = "Cascade" ,)] Users , }

impl Related < super :: users :: Entity > for Entity { fn to () -> RelationDef { Relation :: Users . def () } }

impl ActiveModelBehavior for ActiveModel { }