//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0



use sea_orm :: entity :: prelude :: * ; use super :: sea_orm_active_enums :: ReportStatusEnum ;

# [derive (Clone , Debug , PartialEq , Eq , DeriveEntityModel)] # [sea_orm (table_name = "reports")] pub struct Model { # [sea_orm (primary_key)] pub id : i32 , pub reporter_id : Uuid , pub reported_comment_id : Option < Uuid > , # [sea_orm (column_type = "Text" , nullable)] pub reason : Option < String > , pub menu_id : Option < i32 > , pub r#type : Option < String > , # [sea_orm (column_type = "Text" , nullable)] pub description : Option < String > , pub status : ReportStatusEnum , pub created_at : Option < DateTimeWithTimeZone > , pub resolved_at : Option < DateTimeWithTimeZone > , pub reported_user_id : Option < Uuid > , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { # [sea_orm (belongs_to = "super::comments::Entity" , from = "Column::ReportedCommentId" , to = "super::comments::Column::Id" , on_update = "NoAction" , on_delete = "Cascade" ,)] Comments , # [sea_orm (belongs_to = "super::menus::Entity" , from = "Column::MenuId" , to = "super::menus::Column::Id" , on_update = "NoAction" , on_delete = "Cascade" ,)] Menus , # [sea_orm (belongs_to = "super::users::Entity" , from = "Column::ReportedUserId" , to = "super::users::Column::Id" , on_update = "NoAction" , on_delete = "Cascade" ,)] Users2 , # [sea_orm (belongs_to = "super::users::Entity" , from = "Column::ReporterId" , to = "super::users::Column::Id" , on_update = "NoAction" , on_delete = "Cascade" ,)] Users1 , }

impl Related < super :: comments :: Entity > for Entity { fn to () -> RelationDef { Relation :: Comments . def () } }

impl Related < super :: menus :: Entity > for Entity { fn to () -> RelationDef { Relation :: Menus . def () } }

impl ActiveModelBehavior for ActiveModel { }