//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0



use sea_orm :: entity :: prelude :: * ;

# [derive (Clone , Debug , PartialEq , Eq , DeriveEntityModel)] # [sea_orm (table_name = "system_incidents")] pub struct Model { # [sea_orm (primary_key)] pub id : i32 , pub component : String , pub title : String , # [sea_orm (column_type = "Text")] pub message : String , pub status : String , pub impact : String , pub created_at : Option < DateTimeWithTimeZone > , pub resolved_at : Option < DateTimeWithTimeZone > , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { }

impl ActiveModelBehavior for ActiveModel { }