//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0



use sea_orm :: entity :: prelude :: * ;

# [derive (Clone , Debug , PartialEq , Eq , DeriveEntityModel)] # [sea_orm (table_name = "tags")] pub struct Model { # [sea_orm (primary_key)] pub id : i32 , # [sea_orm (unique)] pub name : String , # [sea_orm (unique)] pub slug : String , pub category : String , pub sort_order : i32 , pub created_at : Option < DateTimeWithTimeZone > , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { # [sea_orm (has_many = "super::dish_tags::Entity")] DishTags , }

impl Related < super :: dish_tags :: Entity > for Entity { fn to () -> RelationDef { Relation :: DishTags . def () } }

impl Related < super :: dishes :: Entity > for Entity { fn to () -> RelationDef { super :: dish_tags :: Relation :: Dishes . def () } fn via () -> Option < RelationDef > { Some (super :: dish_tags :: Relation :: Tags . def () . rev ()) } }

impl ActiveModelBehavior for ActiveModel { }