//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0



use sea_orm :: entity :: prelude :: * ;

# [derive (Clone , Debug , PartialEq , Eq , DeriveEntityModel)] # [sea_orm (table_name = "user_badges")] pub struct Model { # [sea_orm (primary_key , auto_increment = false)] pub user_id : Uuid , # [sea_orm (primary_key , auto_increment = false)] pub badge_id : i32 , pub awarded_at : Option < DateTimeWithTimeZone > , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { # [sea_orm (belongs_to = "super::badges::Entity" , from = "Column::BadgeId" , to = "super::badges::Column::Id" , on_update = "NoAction" , on_delete = "Cascade" ,)] Badges , # [sea_orm (belongs_to = "super::users::Entity" , from = "Column::UserId" , to = "super::users::Column::Id" , on_update = "NoAction" , on_delete = "Cascade" ,)] Users , }

impl Related < super :: badges :: Entity > for Entity { fn to () -> RelationDef { Relation :: Badges . def () } }

impl Related < super :: users :: Entity > for Entity { fn to () -> RelationDef { Relation :: Users . def () } }

impl ActiveModelBehavior for ActiveModel { }