//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0



use sea_orm :: entity :: prelude :: * ;

# [derive (Clone , Debug , PartialEq , Eq , DeriveEntityModel)] # [sea_orm (table_name = "user_blocks")] pub struct Model { # [sea_orm (primary_key , auto_increment = false)] pub blocker_id : Uuid , # [sea_orm (primary_key , auto_increment = false)] pub blocked_id : Uuid , pub created_at : Option < DateTimeWithTimeZone > , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { # [sea_orm (belongs_to = "super::users::Entity" , from = "Column::BlockedId" , to = "super::users::Column::Id" , on_update = "NoAction" , on_delete = "Cascade" ,)] Users2 , # [sea_orm (belongs_to = "super::users::Entity" , from = "Column::BlockerId" , to = "super::users::Column::Id" , on_update = "NoAction" , on_delete = "Cascade" ,)] Users1 , }

impl ActiveModelBehavior for ActiveModel { }