//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0



use sea_orm :: entity :: prelude :: * ; use super :: sea_orm_active_enums :: UserRoleEnum ; use super :: sea_orm_active_enums :: AccountStatusEnum ;

# [derive (Clone , Debug , PartialEq , Eq , DeriveEntityModel)] # [sea_orm (table_name = "users")] pub struct Model { # [sea_orm (primary_key , auto_increment = false)] pub id : Uuid , # [sea_orm (unique)] pub username : String , # [sea_orm (unique)] pub email : String , pub password_hash : String , pub role : UserRoleEnum , pub account_status : AccountStatusEnum , pub karma_score : i32 , pub is_verified : bool , pub avatar_url : Option < String > , # [sea_orm (column_type = "Text" , nullable)] pub bio : Option < String > , pub default_city_slug : Option < String > , pub level : i32 , pub level_progress : i32 , # [sea_orm (unique)] pub google_id : Option < String > , pub created_at : Option < DateTimeWithTimeZone > , pub updated_at : Option < DateTimeWithTimeZone > , pub token_version : i32 , pub opt_out_statistics : bool , pub notif_replies : bool , pub notif_interactions : bool , pub notif_system : bool , pub email_newsletter : bool , pub email_security : bool , pub email_updates : bool , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { # [sea_orm (has_many = "super::api_keys::Entity")] ApiKeys , # [sea_orm (belongs_to = "super::cities::Entity" , from = "Column::DefaultCitySlug" , to = "super::cities::Column::Slug" , on_update = "NoAction" , on_delete = "SetNull" ,)] Cities , # [sea_orm (has_many = "super::comments::Entity")] Comments , # [sea_orm (has_many = "super::contact_messages::Entity")] ContactMessages , # [sea_orm (has_many = "super::dish_votes::Entity")] DishVotes , # [sea_orm (has_many = "super::menu_submissions::Entity")] MenuSubmissions , # [sea_orm (has_many = "super::menu_votes::Entity")] MenuVotes , # [sea_orm (has_many = "super::notifications::Entity")] Notifications , # [sea_orm (has_many = "super::projects::Entity")] Projects , # [sea_orm (has_many = "super::user_badges::Entity")] UserBadges , # [sea_orm (has_many = "super::user_favorites::Entity")] UserFavorites , # [sea_orm (has_many = "super::user_pinned_dishes::Entity")] UserPinnedDishes , # [sea_orm (has_many = "super::user_sessions::Entity")] UserSessions , # [sea_orm (has_many = "super::user_warnings::Entity")] UserWarnings , # [sea_orm (has_many = "super::vote_reactions::Entity")] VoteReactions , }

impl Related < super :: api_keys :: Entity > for Entity { fn to () -> RelationDef { Relation :: ApiKeys . def () } }

impl Related < super :: cities :: Entity > for Entity { fn to () -> RelationDef { Relation :: Cities . def () } }

impl Related < super :: comments :: Entity > for Entity { fn to () -> RelationDef { Relation :: Comments . def () } }

impl Related < super :: contact_messages :: Entity > for Entity { fn to () -> RelationDef { Relation :: ContactMessages . def () } }

impl Related < super :: dish_votes :: Entity > for Entity { fn to () -> RelationDef { Relation :: DishVotes . def () } }

impl Related < super :: menu_submissions :: Entity > for Entity { fn to () -> RelationDef { Relation :: MenuSubmissions . def () } }

impl Related < super :: menu_votes :: Entity > for Entity { fn to () -> RelationDef { Relation :: MenuVotes . def () } }

impl Related < super :: notifications :: Entity > for Entity { fn to () -> RelationDef { Relation :: Notifications . def () } }

impl Related < super :: projects :: Entity > for Entity { fn to () -> RelationDef { Relation :: Projects . def () } }

impl Related < super :: user_badges :: Entity > for Entity { fn to () -> RelationDef { Relation :: UserBadges . def () } }

impl Related < super :: user_favorites :: Entity > for Entity { fn to () -> RelationDef { Relation :: UserFavorites . def () } }

impl Related < super :: user_pinned_dishes :: Entity > for Entity { fn to () -> RelationDef { Relation :: UserPinnedDishes . def () } }

impl Related < super :: user_sessions :: Entity > for Entity { fn to () -> RelationDef { Relation :: UserSessions . def () } }

impl Related < super :: user_warnings :: Entity > for Entity { fn to () -> RelationDef { Relation :: UserWarnings . def () } }

impl Related < super :: vote_reactions :: Entity > for Entity { fn to () -> RelationDef { Relation :: VoteReactions . def () } }

impl Related < super :: badges :: Entity > for Entity { fn to () -> RelationDef { super :: user_badges :: Relation :: Badges . def () } fn via () -> Option < RelationDef > { Some (super :: user_badges :: Relation :: Users . def () . rev ()) } }

impl ActiveModelBehavior for ActiveModel { }