//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0



use sea_orm :: entity :: prelude :: * ;

# [derive (Clone , Debug , PartialEq , Eq , DeriveEntityModel)] # [sea_orm (table_name = "user_pinned_dishes")] pub struct Model { # [sea_orm (primary_key , auto_increment = false)] pub user_id : Uuid , # [sea_orm (primary_key , auto_increment = false)] pub dish_id : i32 , pub created_at : Option < DateTimeWithTimeZone > , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { # [sea_orm (belongs_to = "super::dishes::Entity" , from = "Column::DishId" , to = "super::dishes::Column::Id" , on_update = "NoAction" , on_delete = "Cascade" ,)] Dishes , # [sea_orm (belongs_to = "super::users::Entity" , from = "Column::UserId" , to = "super::users::Column::Id" , on_update = "NoAction" , on_delete = "Cascade" ,)] Users , }

impl Related < super :: dishes :: Entity > for Entity { fn to () -> RelationDef { Relation :: Dishes . def () } }

impl Related < super :: users :: Entity > for Entity { fn to () -> RelationDef { Relation :: Users . def () } }

impl ActiveModelBehavior for ActiveModel { }