//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0



use sea_orm :: entity :: prelude :: * ; use super :: sea_orm_active_enums :: ReactionTypeEnum ;

# [derive (Clone , Debug , PartialEq , Eq , DeriveEntityModel)] # [sea_orm (table_name = "vote_reactions")] pub struct Model { # [sea_orm (primary_key)] pub id : i32 , # [sea_orm (unique_key = "vote_reactions_user_id_comment_id_key")] pub user_id : Uuid , # [sea_orm (unique_key = "vote_reactions_user_id_comment_id_key")] pub comment_id : Uuid , pub reaction_type : ReactionTypeEnum , pub created_at : Option < DateTimeWithTimeZone > , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { # [sea_orm (belongs_to = "super::comments::Entity" , from = "Column::CommentId" , to = "super::comments::Column::Id" , on_update = "NoAction" , on_delete = "Cascade" ,)] Comments , # [sea_orm (belongs_to = "super::users::Entity" , from = "Column::UserId" , to = "super::users::Column::Id" , on_update = "NoAction" , on_delete = "Cascade" ,)] Users , }

impl Related < super :: comments :: Entity > for Entity { fn to () -> RelationDef { Relation :: Comments . def () } }

impl Related < super :: users :: Entity > for Entity { fn to () -> RelationDef { Relation :: Users . def () } }

impl ActiveModelBehavior for ActiveModel { }