-- Kepçe - Seed all 81 Turkish provinces (plate code as id)
BEGIN;

INSERT INTO cities (id, name, slug) VALUES
  (1,  'Adana',          'adana'),
  (2,  'Adıyaman',       'adiyaman'),
  (3,  'Afyonkarahisar', 'afyonkarahisar'),
  (4,  'Ağrı',           'agri'),
  (5,  'Amasya',         'amasya'),
  (6,  'Ankara',         'ankara'),
  (7,  'Antalya',        'antalya'),
  (8,  'Artvin',         'artvin'),
  (9,  'Aydın',          'aydin'),
  (10, 'Balıkesir',      'balikesir'),
  (11, 'Bilecik',        'bilecik'),
  (12, 'Bingöl',         'bingol'),
  (13, 'Bitlis',         'bitlis'),
  (14, 'Bolu',           'bolu'),
  (15, 'Burdur',         'burdur'),
  (16, 'Bursa',          'bursa'),
  (17, 'Çanakkale',      'canakkale'),
  (18, 'Çankırı',        'canakri'),
  (19, 'Çorum',          'corum'),
  (20, 'Denizli',        'denizli'),
  (21, 'Diyarbakır',     'diyarbakir'),
  (22, 'Edirne',         'edirne'),
  (23, 'Elazığ',         'elazig'),
  (24, 'Erzincan',       'erzincan'),
  (25, 'Erzurum',        'erzurum'),
  (26, 'Eskişehir',      'eskisehir'),
  (27, 'Gaziantep',      'gaziantep'),
  (28, 'Giresun',        'giresun'),
  (29, 'Gümüşhane',      'gumushane'),
  (30, 'Hakkari',        'hakkari'),
  (31, 'Hatay',          'hatay'),
  (32, 'Isparta',        'isparta'),
  (33, 'Mersin',         'mersin'),
  (34, 'İstanbul',       'istanbul'),
  (35, 'İzmir',          'izmir'),
  (36, 'Kars',           'kars'),
  (37, 'Kastamonu',      'kastamonu'),
  (38, 'Kayseri',        'kayseri'),
  (39, 'Kırklareli',     'kirklareli'),
  (40, 'Kırşehir',       'kirsehir'),
  (41, 'Kocaeli',        'kocaeli'),
  (42, 'Konya',          'konya'),
  (43, 'Kütahya',        'kutahya'),
  (44, 'Malatya',        'malatya'),
  (45, 'Manisa',         'manisa'),
  (46, 'Kahramanmaraş',  'kahramanmaras'),
  (47, 'Mardin',         'mardin'),
  (48, 'Muğla',          'mugla'),
  (49, 'Muş',            'mus'),
  (50, 'Nevşehir',       'nevsehir'),
  (51, 'Niğde',          'nigde'),
  (52, 'Ordu',           'ordu'),
  (53, 'Rize',           'rize'),
  (54, 'Sakarya',        'sakarya'),
  (55, 'Samsun',         'samsun'),
  (56, 'Siirt',          'siirt'),
  (57, 'Sinop',          'sinop'),
  (58, 'Sivas',          'sivas'),
  (59, 'Tekirdağ',       'tekirdag'),
  (60, 'Tokat',          'tokat'),
  (61, 'Trabzon',        'trabzon'),
  (62, 'Tunceli',        'tunceli'),
  (63, 'Şanlıurfa',      'sanliurfa'),
  (64, 'Uşak',           'usak'),
  (65, 'Van',            'van'),
  (66, 'Yozgat',         'yozgat'),
  (67, 'Zonguldak',      'zonguldak'),
  (68, 'Aksaray',        'aksaray'),
  (69, 'Bayburt',        'bayburt'),
  (70, 'Karaman',        'karaman'),
  (71, 'Kırıkkale',      'kirikkale'),
  (72, 'Batman',         'batman'),
  (73, 'Şırnak',         'sirnak'),
  (74, 'Bartın',         'bartin'),
  (75, 'Ardahan',        'ardahan'),
  (76, 'Iğdır',          'igdir'),
  (77, 'Yalova',         'yalova'),
  (78, 'Karabük',        'karabuk'),
  (79, 'Kilis',          'kilis'),
  (80, 'Osmaniye',       'osmaniye'),
  (81, 'Düzce',          'duzce')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, slug = EXCLUDED.slug;

SELECT setval('cities_id_seq', (SELECT MAX(id) FROM cities));

COMMIT;
