[global]
repo1-path=/opt/kepce/backups/pgbackrest
repo1-retention-full=2
repo1-retention-diff=14
process-max=4
log-level-console=info
log-level-file=debug
compress-type=lz4

[kepce-stanza]
pg1-path=/var/lib/postgresql/data
