pub mod scraper;
pub mod fallback_scraper;
pub mod file_ingest;
pub mod backup_ingest;
pub mod backup_export;
pub mod historical_ingest;
pub mod meal_notifier;
pub mod indexnow;
pub mod enrich_takeaway;
